apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v3ag14cps-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v3ag14cps-python 
  name: v3ag14cps-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v3ag14cps-python 
